### PR TITLE
HackDay 2017-12-07

### PR DESCRIPTION
**Pull request by wdschei**
Lots of little updates, but mainly the Gradle version was bumped and GradleTest was brought in.

### CODE REVIEW

**Comment by kerko** [comment]
i encountered the outdated documentation too, which took me a while to notice. Any plan to accept this?

**Comment by wdschei** [comment]
@kerko This is a side project my team resurrected from the original author's abandon-ware a couple of years ago. We try and keep it updated, but operational fires have taken precedence over getting this finalized. That said, it looks like this and a few more features to make this plugin more Gradle 4.x compatible are bubbling to the top of our backlog.

I'll let you know when this does get merged. Also, if there is anything else you see needs some love, then feel free to open a PR or an issue.

**Comment by kerko** [comment]
Thanks for the heads up. Since it only documentation don’t stress it. If
there is anything to help you get this merged feel free to asks.

**Comment by wdschei** [comment]
Retest this please.

**Pull request merged**
